name: ecommerce
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  hugeicons: ^0.0.7
  image_picker: ^1.1.2
  loading_animation_widget: ^1.3.0
  pinput: ^5.0.1
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  fluttertoast: ^8.2.12
  http: ^1.3.0
  intl_phone_field: ^3.2.0
  webview_flutter: ^4.10.0
  google_sign_in: ^6.1.4
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
#  provider: ^6.0.5
  easy_localization: ^3.0.7
  dropdown_button2: ^2.3.9

#dependency_overrides:
#  provider: 6.0.5

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/translations/

flutter_assets:
  assets_path:
    - assets/images/
    - assets/svgs/
  output_path: lib/core/constants/
  filename: app_images.dart
  field_prefix: null

  fonts:
    - family: kulim
      fonts:
        - asset: fonts/Kulim_Park/KulimPark-Bold.ttf
        - asset: fonts/Kulim_Park/KulimPark-ExtraLight.ttf
        - asset: fonts/Kulim_Park/KulimPark-Light.ttf
        - asset: fonts/Kulim_Park/KulimPark-Regular.ttf
        - asset: fonts/Kulim_Park/KulimPark-SemiBold.ttf
